config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :questions, only: [:index, :show, :new, :create, :update, :edit, :destroy] do
    resources :answers, only: [:create]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

belongs_to :question

validates :description, presence: true, length: { minimum: 50 }

end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers

  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
  validates :creator_id, numericality: { only_integer: true }, allow_blank: true


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @answers = Answer.all
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)

    if @answer.save
      flash[:notice] = 'You have successfully created an answer!'
      redirect_to question_path(@question)
    else
      @question = Question.find(params[:question_id])
      @answers = @question.answers
      flash.now[:notice] = "Your answer must be at least 50 characters long."
      render 'questions/show'
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:description).merge(question: Question.find(params[:question_id]))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
      @questions = Question.all.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order('created_at asc')
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Question is created!"
      redirect_to questions_path
    else
      flash[:notice] = "Invalid input."
      render "new"
    end
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    if @question.save
      flash[:notice] = "You have successfully updated your question!"
      redirect_to @question
    else
      flash.now[:notice] = "Invalid input."
      render 'edit'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    @answers = @question.answers
    @answers.destroy_all
    
    if @answers.empty?
      flash[:notice] = "You have successfully deleted your question!"
      redirect_to questions_path
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, :creator_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<h4>Post an Answer</h4>


<%= form_for [@question, @answer] do |f| %>
  <%= f.label :description, 'Description' %></br>
  <%= f.text_area :description, size: "100x10" %></br>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<h5> <%= flash[:notice] %> </h5>
<%= yield %>

</body>
</html>

app/views/questions/_new.html.erb
<%= button_to 'new', new_question_path, :method => :get %>

app/views/questions/_question.html.erb
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description, "Description" %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.submit "Submit"%>
  </div>

<% end %>

app/views/questions/edit.html.erb
<%= render 'question' %>

<div>
    <%= button_to 'delete', question_path(@question), :method => :delete %>
</div>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul> <% @questions.each do |question| %>
  <li> <%= link_to question.title, question %>"  created by <%= question.creator_id %> ( <%= question.updated_at %> ) </li>
  <% end %>
</ul>

<%= render 'new' %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<h4> <%= flash[:notice] %> </h4>

<%= render 'question' %>

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>
<h5> created at: <%= @question.created_at %> </h5>
<h5> updated at: <%= @question.updated_at %> </h5>

<p>
  <%= @question.description %>
</p>

<%= button_to 'edit', edit_question_path(@question), :method => :get %>
<%= button_to 'delete', question_path(@question), :method => :delete %>

<h4>Answers:</h4>

<% unless @answers.nil? %>
<ul>  <% @answers.each do |answer| %>
  <li> <%= answer.description %> </li>
  <% end %>
</ul>
<% end %>

<%= render 'answers/form' %>